title: Elemental Mystics
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.06673399591818452
  brandStrength: 0.9800042191054672
  lightness: 0.3680504721123725
  brandColors:
    - '#000000'
    - '#221E1F'
    - '#FFFFFF'
    - '#BAB9B9'
    - '#595657'
  rhythmicContrast: 0.1833839404862374
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Elemental Mystics
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.53712
layout_spectrum: 1
