name: Elemental Mystics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53712
title: Elemental Mystics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040707'
    - '#484949'
    - '#b7b8b8'
    - '#959797'
  brandStrength: 0.9800042191054672
  lightness: 0.3680504721123725
  saturation: 0.06673399591818452
  rhythmicContrast: 0.1833839404862374
purpose: []
